### ISSUE TITLE
Cannot sync with websocket fly server

### ISSUE THREAD

**Issue by johanbove** [earthstar-project/user_scripts#8]
Noticed that I could not get the "sync_with_server.ts" and "sync_all.ts" commands to work with my websockets server.
Keep getting the status 404 not found.

```bash
$ user_scripts % deno run -A scripts/sync_with_server.ts 
 ? Pick a share › +data.abc123456
Syncing...
 ? What is the URL of the server you'd you like to sync with? › wss://my-server-domain-at.fly.dev/earthstar-api/v2
Save wss://my-server-domain-at.fly.dev/earthstar-api/v2 to favourite servers? [y/N] y
Syncing...
error: Uncaught (in promise) NetworkError: failed to connect to WebSocket: HTTP error: 404 Not Found
```

The share was added before to the server using an entry in `known_shares.json`.

Is this a problem with my sync server?  It is using ExtensionSyncWebsocket.

Perhaps we need instructions on what kind of server is compatible with these scripts?

Versions:

```bash
deno 1.29.4 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by sgwilym** [comment]
You're getting back a 404 because the your new server does not know how to serve path you're requesting (`/earthstar-api/v2`). This path was used by v7 - v9 Earthstar servers for the sync protocol those versions used.

So what's the new sync endpoint? It's configured here: https://github.com/earthstar-project/earthstar-server-fly/blob/0aa786337254d3c12b8631290163b59c9da6e183/server.ts#L31

So you can use https://my-server-domain-at.fly.dev/sync.

Earthstar will handle the protocol switching, you don't need to use `wss://`. :)

Let me know if this helps!

**Comment by johanbove** [comment]
That's good to know - but guess I will need to update my server for this work.

**Comment by sgwilym** [comment]
I see, I misunderstood. Sorry that it wasn't clearer that existing servers would not be able to sync with v10. It is possible to use es4 in v10, and upgrade the sqlite db automatically.

**Comment by johanbove** [comment]
Thanks for the clarification.
